version: 2.1
commands:
  build-and-test:
    steps:
      - checkout
      - restore_cache:
          name: Restore cache (main)
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore cache (example)
          keys:
            - v1-dependencies-{{ checksum "examples/simple/yarn.lock" }}
      - run:
          name: Install dependencies (main)
          command: yarn install
      - run:
          name: Build source (main)
          command: yarn build
      - run:
          name: Build source (example)
          command: yarn build:examples/simple
      - save_cache:
          name: Save cache (main)
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - save_cache:
          name: Save cache (example)
          paths:
            - examples/simple/node_modules
          key: v1-dependencies-{{ checksum "examples/simple/yarn.lock" }}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test

jobs:
  node-v10:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - build-and-test
  node-v12:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - build-and-test
  node-v14:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - build-and-test

workflows:
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - node-v14
