version: 2.1
commands:
  build-and-test:
    steps:
      - checkout
      - run:
          name: Install dependencies (main)
          command: npm install
      - run:
          name: Build next-i18next
          command: npm run build
      - run:
          name: Install examples
          command: npm run install:examples
      - run:
          name: Replace examples install with repo build
          command: npm run move-build-to-examples
      - run:
          name: Build examples
          command: npm run build:examples
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Typecheck
          command: npm run typecheck
      - run:
          name: Test
          command: npm test
      - run:
          name: e2e
          command: npm run test:e2e
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos

jobs:
  # node-v12:
  #   docker:
  #     - image: circleci/node:12-browsers
  #   steps:
  #     - build-and-test
  # node-v14:
  #   docker:
  #     - image: circleci/node:14-browsers
  #   steps:
  #     - build-and-test
  node-v16:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - build-and-test
  # node-v18:
  #   docker:
  #     - image: cimg/node:18.4
  #   steps:
  #     - build-and-test

workflows:
  node-multi-build:
    jobs:
      # - node-v12
      # - node-v14
      # - node-v16
      - node-v18
