version: 2.1
commands:
  build-and-test:
    steps:
      - checkout
      - run:
          name: Install dependencies (main)
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: e2e
          command: yarn test:e2e
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos

jobs:
  node-v12:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - build-and-test
  node-v14:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - build-and-test
  node-v16:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - build-and-test
  node-v18:
    docker:
      - image: circleci/node:18-browsers
    steps:
      - build-and-test

workflows:
  node-multi-build:
    jobs:
      - node-v12
      - node-v14
      - node-v16
      - node-v18
